/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ChainhookAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "ChainhookDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "ChainhookPlatform": {
      "type": "sst.aws.Nextjs"
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Helius": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "HeliusApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "HeliusRpcUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusWebhookId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "chainhookVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}